"""add column phone to users tables

Revision ID: 059dbc52f20d
Revises: 4cf1044113a0
Create Date: 2026-06-30 21:04:22.632643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059dbc52f20d'
down_revision = '4cf1044113a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
