"""change structure to multi-contributor

Revision ID: 45c92b83d6e3
Revises: 83950f82b16c
Create Date: 2026-05-11 22:17:28.107820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45c92b83d6e3'
down_revision = '83950f82b16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.Column('drive_folder_link', sa.String(length=255), nullable=False),
    sa.Column('price_digital', sa.Integer(), nullable=True),
    sa.Column('allow_physical_print', sa.Boolean(), nullable=True),
    sa.Column('status_ai', sa.Enum('idle', 'processing', 'completed', 'error'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photographer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('events_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('price_digital')
        batch_op.drop_column('drive_folder_link')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status_ai')
        batch_op.drop_column('photographer_id')
        batch_op.drop_column('allow_physical_print')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_physical_print', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photographer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status_ai', mysql.ENUM('idle', 'processing', 'completed', 'error'), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('drive_folder_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('price_digital', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('events_ibfk_1'), 'users', ['photographer_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('location_name')

    op.drop_table('event_albums')
    # ### end Alembic commands ###
