"""hapus city_id dan ganti ke postal_code

Revision ID: 4c37ea06adb7
Revises: 856eeccfd729
Create Date: 2026-06-25 00:33:38.362074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c37ea06adb7'
down_revision = '856eeccfd729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.Integer(), nullable=True))
        batch_op.drop_column('city_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.Integer(), nullable=True))
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('postal_code')

    with op.batch_alter_table('studios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
