"""tambah kolom gambar di event

Revision ID: 7a526eeb1b5d
Revises: e115f6f30aec
Create Date: 2026-06-24 19:05:33.106266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a526eeb1b5d'
down_revision = 'e115f6f30aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
