"""add price and printing options to event

Revision ID: 83950f82b16c
Revises: 41deb0b53bf6
Create Date: 2026-05-11 21:38:16.848142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83950f82b16c'
down_revision = '41deb0b53bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.Enum('print', 'frame'), nullable=True),
    sa.Column('additional_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_digital', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_physical_print', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('allow_physical_print')
        batch_op.drop_column('price_digital')

    op.drop_table('studio_services')
    # ### end Alembic commands ###
