"""tambah city_id user dan berat layanan

Revision ID: 856eeccfd729
Revises: d3e3e3b0752b
Create Date: 2026-06-24 22:21:06.006513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856eeccfd729'
down_revision = 'd3e3e3b0752b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_gram', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city_id')

    with op.batch_alter_table('studio_services', schema=None) as batch_op:
        batch_op.drop_column('weight_gram')

    # ### end Alembic commands ###
