"""add photo and face models

Revision ID: 8ea9f6e91d15
Revises: d762f608f2da
Create Date: 2026-05-12 23:36:18.782446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ea9f6e91d15'
down_revision = 'd762f608f2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gdrive_file_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('original_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('preview_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('photos_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'event_albums', ['album_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('photos_ibfk_1'), 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('preview_path',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('original_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('file_name')
        batch_op.drop_column('gdrive_file_id')
        batch_op.drop_column('album_id')

    # ### end Alembic commands ###
