"""modify tables withdrawls

Revision ID: b31f2e937274
Revises: 059dbc52f20d
Create Date: 2026-06-30 21:34:50.830300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b31f2e937274'
down_revision = '059dbc52f20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('photographer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photographer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photographer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'completed', 'rejected'),
               type_=sa.Enum('pending', 'success', 'failed'),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('withdrawals_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['photographer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('withdrawals_ibfk_1'), 'wallets', ['wallet_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'success', 'failed'),
               type_=mysql.ENUM('pending', 'completed', 'rejected'),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('photographer_id')

    op.drop_table('event_contributors')
    # ### end Alembic commands ###
