"""tambah gambar di studio services

Revision ID: d3e3e3b0752b
Revises: 7a526eeb1b5d
Create Date: 2026-06-24 22:03:59.195319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3e3e3b0752b'
down_revision = '7a526eeb1b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('service_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('service_type',
               existing_type=mysql.ENUM('print', 'frame'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studio_services', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=mysql.ENUM('print', 'frame'),
               nullable=True)
        batch_op.alter_column('service_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
