"""Rename firebase_uid to provider_uid

Revision ID: e115f6f30aec
Revises: 8ea9f6e91d15
Create Date: 2026-06-16 21:27:42.466768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e115f6f30aec'
down_revision = '8ea9f6e91d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_uid', sa.String(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('firebase_uid'))
        batch_op.create_unique_constraint(None, ['provider_uid'])
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('firebase_uid'), ['firebase_uid'], unique=True)
        batch_op.drop_column('provider_uid')

    # ### end Alembic commands ###
